---
apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: k3s-default
servers: 1
agents: 3
ports:
  - port: 443:443
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik,metrics-server
        nodeFilters:
          - server:*
      - arg: --disable-helm-controller 
        nodeFilters:
          - server:*

